version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["./bin/rails", "server", "-b", "0.0.0.0", "-p", "3001"]
    volumes:
      - .:/rails
    ports:
      - "3001:3001"
    environment:
      RAILS_ENV: development
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      TEST_DATABASE_USERNAME: postgres
      TEST_DATABASE_PASSWORD: postgres
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce_app_development
      POSTGRES_MULTIPLE_DATABASES: ecommerce_app_test
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ecommerce_app_development"]
      interval: 10s
      retries: 5
      timeout: 5s

volumes:
  postgres_data: