default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: gvicencotti
  password: senha

development:
  <<: *default
  database: ecommerce_app_development

test:
  <<: *default
  database: ecommerce_app_test

production:
  <<: *default
  database: ecommerce_app_production
  username: ecommerce_app
  password: <%= ENV['ECOMMERCE_APP_DATABASE_PASSWORD'] %>
